- name: Ensure PXE-related packages are present
  yum: state=present name={{ item }}
  with_items:
    - syslinux
    - tftp-server
    - tftp
  when: pxesrv_active

- name: Create directory for pxelinux configs
  file: path=/var/lib/tftpboot/pxelinux.cfg state=directory
  when: pxesrv_active

- name: Create directory for pxelinux configs bind mount
  file: path=/usr/share/syslinux/{{ item }} state=directory
  with_items:
    - pxelinux.cfg
    - centos7
  when: pxesrv_active

- name: Copy default pxelinux config
  template: src=default dest=/var/lib/tftpboot/pxelinux.cfg/default
  when: pxesrv_active

- name: Create directory for CentOS kernel and initrd
  file: path=/var/lib/tftpboot/centos7 state=directory
  when: pxesrv_active

- name: Create bind mount for CentOS kernel and initrd, pxelinux.cfg
  mount: src=/var/lib/tftpboot/{{ item }} name=/usr/share/syslinux/{{ item }} fstype=none opts=bind state=mounted
  with_items:
    - centos7
    - pxelinux.cfg
  when: pxesrv_active

- name: Create lame symlink because I cannot stop client from using server IP
  file: src=/usr/share/syslinux/pxelinux.0 dest=/usr/share/syslinux/10.10.10.1.0 state=link

- name: Ensure CentOS 7 iso directory
  file: path={{ home }}/iso state=directory
  when: pxesrv_active

- name: Check for CentOS 7 ISO
  stat: path={{ home }}/iso/{{ c7file }} get_checksum=false get_md5=true
  register: st
  when: pxesrv_active

- name: Download CentOS 7 DVD ISO
  get_url:
    dest: "{{ home }}/iso/{{ c7file }}"
    url: "{{ c7rpath }}/{{ c7file }}"
    sha256sum: "{{ c7sha256 }}"
  when: pxesrv_active and (st.stat.md5 is not defined or st.stat.md5 != "{{ c7md5 }}")

- name: Ensure mountpoint for CentOS 7 DVD ISO
  file: path=/mnt/centos7 state=directory
  when: pxesrv_active

- name: Ensure CentOS 7 DVD ISO mounted
  mount:
    name: /mnt/centos7
    src: "{{ home }}/iso/{{ c7file }}"
    opts: loop
    fstype: iso9660
    state: mounted
  when: pxesrv_active

- name: Copy CentOS kernel and initrd to TFTP area
  command: rsync /mnt/centos7/images/pxeboot/{{ item }} /var/lib/tftpboot/centos7
  with_items:
    - vmlinuz
    - initrd.img
  when: pxesrv_active
