---
- hosts: all
  vars:
    - home: "{{ lookup('env', 'HOME') }}"
    - pxeserver: 10.10.10.1
    - c7rpath: http://mirror.atlanticmetro.net/centos/7/isos/x86_64/
    - c7file: CentOS-7-x86_64-DVD-1503-01.iso
    - c7md5: 99e450fb1b22d2e528757653fcbf5fdc
    - c7sha256: 85bcf62462fb678adc0cec159bf8b39ab5515404bc3828c432f743a1b0b30157
    - firewall_active: no
    - pxesrv_active: no
    - mhttpd_path: /usr/local/sbin
    - mhttpd_md5: c9f3131179351ff5267a2aa6adb9e1d3
    - mhttpd_sha256: 0829969f6e8cd7263dfc0eeeaddc92b9a564c7a68bc72b2d1b4af6c2198d9931
    - mhttpd_rpath: http://acme.com/software/mini_httpd
    - mhttpd_dir: mini_httpd-1.21
    - mhttpd_tgz: "{{ mhttpd_dir }}.tar.gz"
    - mhttpd_active: no
  sudo: yes
  pre_tasks:
    - name: Ensure yum-managed system packages installed
      yum: state=present name={{ item }}
      with_items:
        - dnsmasq
        - epel-release
        - firewalld
        - psmisc
        - rsync
    - name: Ensure yum-managed user packages installed
      yum: state=present name={{ item }}
      with_items:
        - bzip2
        - firefox
        - lynx
        - screen
        - strace
        - tigervnc
        - tigervnc-server
        - xorg-x11-utils
        - xterm

#    # Set forwarding in /proc and in the sysctl file, reloading if necessary
#    - name: Turn on IPv4 forwarding
#      sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
#    - name: Install dnsmasq configuration
#      template: dest=/etc/dnsmasq.conf src=dnsmasq.conf
#    - name: Ensure dnsmasq service runs
#      service: name=dnsmasq enabled=yes state=started
#
  roles:
    - firewall
    - pxesrv
    - mini_httpd
